Agriculture: Cooked Sardine
zunath/SWLOR_NWN pull request #1697
Opened 2023-02-12 06:28 UTC by Valo56

Issue 1683: Fix for Cooked Sardine quest. There was a recipe for Sardine Ball. This item does exist in the module but has no item properties. Cooked Sardine does exist in the module and has the appropriate item properties and resref for the indicated quest. This should fix the issue and make it possible to complete the quest.

2023-02-12 12:41 UTC, zunath commented on SWLOR.Game.Server/Service/CraftService/RecipeType.cs
> -        SardineBall = 2094,
Need a migration for this change. Anyone who already crafted the Sardine Ball will break after updating this.

2023-02-12 12:50 UTC, zunath requested changes
Requesting changes

2023-02-27 01:47 UTC, Valo56 commented
Wookies can now be much taller. Slightly taller Trandoshans, Droids and Zabraks.
Facelift to Viscara and Mon Cala station exteriors.
New Viscaran starport (uses old dockhand in same area as before, with transition to a new starport interior which may serve as a nice RP hub, no migration necessary).
Reverted changes to Sardine Ball recipe, it's back in, but now has item properties and is a Force Defense/HP alternative to the Cooked Sardine which is Physical Defense/HP. No migration necessary.
DM's will be able to spawn in all new station placeable appearances.
Two new prefabs. A last adjustment to a space prefab as its skybox was obnoxious.

2023-03-02 22:51 UTC, Valo56 commented
Closing PR. Will polish and submit each change individually in a more clean manner on their own branches.

2023-03-02 22:51 UTC, closed without merging