Dantooine  Electric Boogaloo
zunath/SWLOR_NWN pull request #1706
Opened 2023-03-14 16:16 UTC by Scorchys12

Dantooine Planet update

2023-04-05 15:53 UTC, zunath commented on SWLOR.Game.Server/Enumeration/PlanetType.cs
> +    "Dantooine - ",
Please fix the tabbing here. It should be lined up similar to the other planet entries.

2023-04-05 16:05 UTC, zunath commented
+20 Accuracy & Force Attack for commonly acquired ingredients is too high. Either reduce the amount it increases and reduce its level or change the ingredients needed to use more difficult to obtain items.

2023-04-05 16:12 UTC, zunath commented on SWLOR.Game.Server/Feature/RecipeDefinition/SmitheryRecipeDefinition/RangedRecipes.cs
> +            // Bol Rifle
This is stronger than even the Chiro Rifle. If it's supposed to be on par with the Chiro then please reduce its DMG and give it equivalent additional stats.

2023-04-05 16:18 UTC, zunath commented on Module/uti/dan_h_cloak.uti.json
> +{
Please mark this item as identified under properties.

2023-04-05 16:20 UTC, zunath commented on Module/uti/dan_heavy_armor.uti.json
> +{
Please mark this item as identified.

2023-04-05 16:22 UTC, zunath commented on Module/uti/dan_hyper_gloves.uti.json
> +{
Please mark this item as identified.

2023-04-05 16:24 UTC, zunath commented on Module/uti/dan_kin_boots.uti.json
> +{
The name of the item is "Boots" but the perk needed is "Leggings". Please correct so it's consistently named.

2023-04-05 16:32 UTC, zunath commented on Module/uti/dan_spear.uti.json
>    "__data_type": "UTI ",
55 DMG is obnoxiously high. Please reduce.

2023-04-05 16:35 UTC, zunath commented on Module/uti/krafters_kebab.uti.json
> +{
+20 Control to all skills is too high. Please reduce.

2023-04-05 16:35 UTC, zunath commented on Module/uti/krafters_kebab.uti.json
> +  "__data_type": "UTI ",
Please set the identified flag to true under properties.

2023-04-05 16:36 UTC, zunath commented on Module/uti/map_072.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:37 UTC, zunath commented on Module/uti/map_073.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:37 UTC, zunath commented on Module/uti/map_074.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:37 UTC, zunath commented on Module/uti/map_075.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:37 UTC, zunath commented on Module/uti/map_076.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:38 UTC, zunath commented on Module/uti/map_077.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:38 UTC, zunath commented on Module/uti/map_078.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:38 UTC, zunath commented on Module/uti/map_70.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:38 UTC, zunath commented on Module/uti/map_70.uti.json
> +  "__data_type": "UTI ",
Please correct the resref on this item. It's missing the leading zero

2023-04-05 16:38 UTC, zunath commented on Module/uti/map_71.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:39 UTC, zunath commented on Module/uti/map_71.uti.json
> +  "__data_type": "UTI ",
Please correct the resref on this item. It is missing the leading zero.

2023-04-05 16:42 UTC, zunath commented on Module/uti/munch_fungusb.uti.json
> +{
Please set the identified property to true under properties.

2023-04-05 16:42 UTC, zunath commented on Module/uti/recipe_bolrifle.uti.json
> +      "0": "Blueprint: Bol Rilfe"
Typo here. Rilfe -> Rifle

2023-04-05 16:44 UTC, zunath commented on Module/are/dan_junglemount.are.json
> +      "0": "Dantooine -  Jungle Mountain"
Typo: extra space between "-" and "Jungle"

2023-04-05 16:46 UTC, zunath commented on Module/are/dan_warehouse.are.json
> +      "0": "Dantooine - Abandon Warehouse"
Typo: Should be "Abandoned"

2023-04-05 16:48 UTC, zunath commented on Module/utw/fp_danmount.utw.json
> +{
Please change this resref to be consistent with the others. If the numbering is right, this should be "fp_035"

2023-04-05 16:57 UTC, zunath commented on SWLOR.Game.Server/Service/AchievementService/AchievementType.cs
> +        [Achievement("Explore Dantooine Orbit", "Explore Dantooine's Orbit'.", true)]
Typo: extra ' after Orbit.

2023-04-05 16:58 UTC, zunath commented on SWLOR.Game.Server/Service/AchievementService/AchievementType.cs
> +        [Achievement("Explore Dantooine Field", "Explore Dantooine's Fields.", true)]
Typo: Field -> Fields, for consistency's sake

2023-04-05 16:58 UTC, zunath commented on SWLOR.Game.Server/Service/AchievementService/AchievementType.cs
> +        [Achievement("Explore Dantooine Kinrath Cave", "Explore Dantooine's Kinrath Tunnels.", true)]
Minor issue: Please make it consistent. Is it Caves or Tunnels?

2023-04-05 16:59 UTC, zunath commented on SWLOR.Game.Server/Service/AchievementService/AchievementType.cs
> +        [Achievement("Explore Dantooine South Plains", "Explore Dantooine's Tribe.", true)]
Description doesn't match the area. Please correct

2023-04-05 16:59 UTC, zunath commented on SWLOR.Game.Server/Service/AchievementService/AchievementType.cs
> +        [Achievement("Explore Dantooine Abandon Warehouse", "Explore Dantooine's Abandon Base.", true)]
Abandon -> Abandoned. Also, consistency here too - is it a Warehouse or a Base? Please update to reflect appropriately.

2023-04-05 17:00 UTC, zunath commented on SWLOR.Game.Server/Service/AchievementService/AchievementType.cs
> +        ExploreDantooineAbandonWare = 118,
Please correct the enum name to match too. And fully spell out words, please

2023-04-05 17:01 UTC, zunath commented on SWLOR.Game.Server/Service/KeyItemService/KeyItemType.cs
> +        DantooineMountianJunglesMap = 75,
Typo: Mountian -> Mountain

2023-04-05 17:01 UTC, zunath commented on SWLOR.Game.Server/Service/KeyItemService/KeyItemType.cs
> +        [KeyItem(KeyItemCategoryType.Maps, "Dantooine - Abandon Warehouse  Map", true, "Map of the Abandon Warehouse Base on Dantooine.")]
Typo: Abandon -> Abandoned

2023-04-05 17:02 UTC, zunath commented on SWLOR.Game.Server/Service/KeyItemService/KeyItemType.cs
> +        [KeyItem(KeyItemCategoryType.Maps, "Dantooine - Abandon Warehouse  Map", true, "Map of the Abandon Warehouse Base on Dantooine.")]
You also have an extra space after "Warehouse" which should be removed.

2023-04-05 17:02 UTC, zunath commented on SWLOR.Game.Server/Service/KeyItemService/KeyItemType.cs
> +        DantooineWareHouseMap = 77,
Typo: WareHouse -> Warehouse

2023-04-05 17:02 UTC, zunath commented on SWLOR.Game.Server/Service/KeyItemService/KeyItemType.cs
> +        DantooineCanyonRivereMap = 78,
Typo: Rivere -> River

2023-04-05 17:03 UTC, zunath requested changes
Changes requested

2023-04-06 21:10 UTC, Scorchys12 commented on Module/uti/krafters_kebab.uti.json
> +{
i reduced it down to 7+ to all, though unsure if that's too low with the ingredients required.

2023-04-16 00:52 UTC, zunath commented
New PR submitted due to lack of permissions to push changes to this one. https://github.com/zunath/SWLOR_NWN/pull/1717

2023-04-16 00:52 UTC, closed without merging